plugins {
    id 'com.android.library'
}

ext.pluginVersionCode = 7
ext.pluginVersionName = "1.4.0"

android {
    namespace 'org.godotengine.godot.plugin.googleplaybilling'
    compileSdkVersion 36

    defaultConfig {
        minSdkVersion 23
        targetSdkVersion 36
        versionCode pluginVersionCode
        versionName pluginVersionName
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            output.outputFileName = "GodotGooglePlayBilling.$pluginVersionName.${variant.name}.aar"
        }
    }
}

dependencies {
    implementation "androidx.legacy:legacy-support-v4:1.0.0"
    implementation 'com.android.billingclient:billing:9.1.0'
    compileOnly fileTree(dir: 'libs', include: ['godot-lib*.aar'])
}
